services:
  - type: web
    name: ch14-email-java
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
    buildCommand: echo "Building with Docker"
    startCommand: echo "Starting with Docker"